### ISSUE TITLE
Incorrect architecture detected after build with newly applied retpoline patch

### ISSUE THREAD

**Issue by klikevil** [HacKurx/public-sharing#2]
This may be a systemd bug and not with the kernel itself, but it looks like it incorrectly gets detected as x66_64 now with this kernel?
![badarch1](https://user-images.githubusercontent.com/32278206/37002710-988b8ff4-2098-11e8-85c4-bba79ddad69a.png)
![sorcery](https://user-images.githubusercontent.com/32278206/37002748-b003ccb4-2098-11e8-85e7-1018d7d95059.png)

**Comment by klikevil** [comment]
I think I might have a guess as to what is causing it though

It looks like you are overriding the syscall numbers for SYS_getcpu instead of defining them as _ like __NR_getcpu in syscall.h
```

 +#ifndef SYS_getcpu
 +# ifdef __x86_64__
 +#  define SYS_getcpu 309
 +# else
 +#  define SYS_getcpu 318
 +# endif
 +#endif

```

I'm not quire sure what syscall 309 is, but yeah it causes systemd to break (which is cancer to linux anyway in my opinion, i'm only using it because I was forced to and they won't just let me flat out install gentoo on my VM up here). If you could point me in the right direction of where the architecture is being incorrectly determined like that or since this isn't going to be deployed to other systems a way I could make it just return a fake architecture to trick systemd it would be much appreciated because all the other stuff seems to work in my chroot from the rescue shell, the rest of the system doesn't give a crap that it's reporting the wrong arch only systemd ><

**Comment by theLOICofFRANCE** [comment]
I have not changed the value of UTS_MACHINE.
https://www.mail-archive.com/linux-kbuild@vger.kernel.org/msg00147.html

I did nothing more than the upstream...
https://github.com/torvalds/linux/commits/master/tools/testing/selftests/x86/test_vsyscall.c

**Comment by klikevil** [comment]
Probably with systemd then the bane of linux I'll go ahead and close this issue.

**Comment by theLOICofFRANCE** [comment]
Start the VM with qemu or kvm to see. Test with various processor architecture to emulate : 

`qemu-system-x86_64 -cpu ?`
